<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Booking Mobil — {{ config('app.name') }}</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-slate-50 text-slate-900"><header class="sticky top-0 z-20 bg-white/90 backdrop-blur border-b"><div class="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between"><a href="{{ route('home') }}" class="font-black text-xl">{{ config('app.name') }}</a><a href="{{ route('portal.login') }}" class="text-sm font-bold text-blue-700">Portal pelanggan</a></div></header>
<main class="max-w-6xl mx-auto px-4 py-10"><div class="mb-8"><p class="text-blue-700 font-bold">BOOKING REAL-TIME</p><h1 class="text-3xl md:text-5xl font-black mt-2">Pilih mobil, cek harga, langsung booking.</h1><p class="text-slate-600 mt-3">Harga mengikuti periode, pajak, promo, dan dynamic pricing dari database.</p></div>
@if($errors->any())<div class="mb-6 rounded-xl bg-red-50 text-red-700 p-4">{{ $errors->first() }}</div>@endif
<form id="booking-form" method="POST" action="{{ route('booking.store') }}" class="grid lg:grid-cols-3 gap-6">@csrf
<section class="lg:col-span-2 grid sm:grid-cols-2 gap-4">@foreach($vehicles as $v)<label class="bg-white rounded-2xl border p-5 cursor-pointer hover:-translate-y-1 hover:shadow-xl transition"><input type="radio" name="vehicle_id" value="{{ $v->id }}" class="mr-2" required><span class="font-black">{{ $v->name }}</span><div class="text-sm text-slate-500 mt-2">{{ $v->plate_number }} · {{ $v->transmission }} · {{ $v->seat_count }} kursi</div><div class="text-blue-700 font-black mt-3">Rp {{ number_format($v->daily_rate,0,',','.') }}/hari</div></label>@endforeach</section>
<aside class="bg-white rounded-2xl border p-5 h-fit space-y-4"><input name="name" required placeholder="Nama lengkap" class="w-full rounded-xl border p-3"><input name="email" type="email" required placeholder="Email" class="w-full rounded-xl border p-3"><input name="phone" required placeholder="Nomor WhatsApp" class="w-full rounded-xl border p-3"><select name="pickup_location_id" required class="w-full rounded-xl border p-3"><option value="">Lokasi pengambilan</option>@foreach($locations as $l)<option value="{{ $l->id }}">{{ $l->name }}</option>@endforeach</select><input name="start_date" type="date" min="{{ today()->toDateString() }}" required class="w-full rounded-xl border p-3"><input name="end_date" type="date" required class="w-full rounded-xl border p-3"><select name="rental_type" class="w-full rounded-xl border p-3"><option value="self_drive">Lepas kunci</option><option value="with_driver">Dengan sopir</option><option value="airport_transfer">Airport transfer</option><option value="corporate">Corporate</option></select>
@if($addons->isNotEmpty())<fieldset class="rounded-xl border p-3"><legend class="px-1 text-sm font-bold">Tambahan</legend><div class="space-y-2">@foreach($addons as $addon)<label class="flex items-center justify-between gap-3 text-sm"><span><input type="checkbox" name="addon_ids[]" value="{{ $addon->id }}" class="mr-2">{{ $addon->name }}</span><b>Rp {{ number_format($addon->price,0,',','.') }}</b></label>@endforeach</div></fieldset>@endif
<input name="promo_code" placeholder="Kode promo (opsional)" class="w-full rounded-xl border p-3 uppercase"><div id="quote" class="hidden rounded-xl bg-blue-50 p-4 text-sm"></div><textarea name="notes" placeholder="Catatan" class="w-full rounded-xl border p-3"></textarea><button class="w-full rounded-xl bg-blue-700 text-white font-black py-3 hover:bg-blue-800">Kirim Booking</button></aside></form><div class="mt-6">{{ $vehicles->links() }}</div></main><script>const f=document.getElementById('booking-form'),q=document.getElementById('quote');async function quote(){const v=f.querySelector('[name=vehicle_id]:checked'),s=f.start_date.value,e=f.end_date.value;if(!v||!s||!e)return;const addonIds=[...f.querySelectorAll('[name="addon_ids[]"]:checked')].map(x=>x.value);const r=await fetch(@json(route('booking.quote')),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':f._token.value},body:JSON.stringify({vehicle_id:v.value,start_date:s,end_date:e,rental_type:f.rental_type.value,addon_ids:addonIds,promo_code:f.promo_code.value})});if(!r.ok)return;const d=await r.json();q.classList.remove('hidden');q.innerHTML=`<b>Estimasi ${d.duration_days} hari</b><br>Tarif efektif: Rp ${Number(d.effective_daily_rate).toLocaleString('id-ID')}<br>Tambahan: Rp ${Number(d.addon_total).toLocaleString('id-ID')}<br>Diskon: Rp ${Number(d.discount_amount).toLocaleString('id-ID')}<br><strong class="text-lg">Total: Rp ${Number(d.total).toLocaleString('id-ID')}</strong>`}f.addEventListener('change',quote);f.promo_code.addEventListener('blur',quote);</script></body></html>
