@extends('portal.layout')
@section('content')
<div class="mb-8"><p class="font-mono text-xs uppercase tracking-[.2em] text-blue-600">Ringkasan akun</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Halo, {{ $customer->name }}</h1><p class="mt-2 text-slate-500">Semua perjalanan dan tagihan Anda dalam satu layar.</p></div>
<div class="grid gap-4 sm:grid-cols-3"><div class="lift rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-500">Pesanan aktif</p><strong class="mt-2 block text-3xl">{{ $orders->whereIn('status',['active','checked_out','overdue'])->count() }}</strong></div><div class="lift rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-500">Total transaksi</p><strong class="mt-2 block text-3xl">{{ $customer->total_orders }}</strong></div><div class="lift rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white"><p class="text-sm text-slate-400">Total belanja</p><strong class="mt-2 block text-2xl">Rp {{ number_format($customer->total_spent,0,',','.') }}</strong></div></div>
<div class="mt-8 grid gap-6 lg:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white"><div class="flex items-center justify-between border-b p-5"><h2 class="font-bold">Pesanan terbaru</h2><a href="{{ route('portal.orders') }}" class="text-sm font-semibold text-blue-600">Lihat semua</a></div><div class="divide-y">@forelse($orders as $order)<div class="flex items-center justify-between gap-4 p-5"><div><strong>{{ $order->order_number }}</strong><p class="text-sm text-slate-500">{{ $order->vehicle?->name }} · {{ $order->start_date?->format('d M') }}–{{ $order->end_date?->format('d M Y') }}</p></div><x-portal.status-badge :status="$order->status" type="order" /></div>@empty<div class="p-8 text-center text-slate-500">Belum ada pesanan.</div>@endforelse</div></section>
<section class="rounded-2xl border border-slate-200 bg-white"><div class="flex items-center justify-between border-b p-5"><h2 class="font-bold">Invoice terbaru</h2><a href="{{ route('portal.invoices') }}" class="text-sm font-semibold text-blue-600">Lihat semua</a></div><div class="divide-y">@forelse($invoices as $invoice)<div class="flex items-center justify-between p-5"><div><strong>{{ $invoice->invoice_number }}</strong><p class="text-sm text-slate-500">Jatuh tempo {{ $invoice->due_date?->format('d M Y') }}</p></div><strong>Rp {{ number_format($invoice->balance_due,0,',','.') }}</strong></div>@empty<div class="p-8 text-center text-slate-500">Belum ada invoice.</div>@endforelse</div></section></div>
<section class="mt-8 rounded-2xl border border-slate-200 bg-white"><div class="border-b p-5"><h2 class="font-bold">Linimasa booking</h2><p class="mt-1 text-sm text-slate-500">Status booking terbaru Anda, dari reservasi hingga serah terima.</p></div><div class="divide-y">@forelse($bookings as $booking)<article class="p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><strong>{{ $booking->booking_number }}</strong><p class="text-sm text-slate-500">{{ $booking->vehicle?->name }} · {{ $booking->start_date?->format('d M') }}–{{ $booking->end_date?->format('d M Y') }}</p></div><x-portal.status-badge :status="$booking->status" type="booking" /></div><ol class="mt-4 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><li>@if($booking->created_at)<span class="{{ 'font-semibold text-slate-700' }}">Reservasi {{ $booking->created_at->format('d M Y H:i') }}</span>@endif</li><li>@if($booking->confirmed_at)<span class="font-semibold text-slate-700">Dikonfirmasi {{ $booking->confirmed_at->format('d M Y H:i') }}</span>@endif</li><li>@if($booking->status === 'converted')<span class="font-semibold text-emerald-700">Menjadi pesanan</span>@endif</li><li>@if($booking->cancelled_at)<span class="font-semibold text-red-600">Dibatalkan {{ $booking->cancelled_at->format('d M Y H:i') }}</span>@endif</li></ol></article>@empty<div class="p-8 text-center text-slate-500">Belum ada booking. <a href="{{ route('storefront.catalog') }}" class="font-semibold text-blue-600">Mulai cari mobil</a>.</div>@endforelse</div></section>
<section class="mt-8 rounded-2xl border border-slate-200 bg-white"><div class="border-b p-5"><h2 class="font-bold">Deposit</h2><p class="mt-1 text-sm text-slate-500">Deposit bukan biaya sewa — dikembalikan penuh setelah kendaraan diperiksa.</p></div><div class="divide-y">@forelse($deposits as $deposit)<div class="flex items-center justify-between gap-4 p-5"><div><strong>Rp {{ number_format($deposit->amount,0,',','.') }}</strong><p class="text-sm text-slate-500">{{ $deposit->rentalOrder?->order_number }}@if($deposit->refunded_at) · dikembalikan {{ $deposit->refunded_at->format('d M Y') }}@if($deposit->refund_amount !== null) (Rp {{ number_format($deposit->refund_amount,0,',','.') }})@endif@elseif($deposit->reference_number) · ref {{ $deposit->reference_number }}@endif</p>@if($deposit->notes)<p class="mt-1 text-xs text-slate-400">{{ $deposit->notes }}</p>@endif</div><x-portal.status-badge :status="$deposit->deposit_status" type="deposit" /></div>@empty<div class="p-8 text-center text-slate-500">Belum ada deposit tercatat.</div>@endforelse</div></section>
<section class="mt-8 rounded-2xl border border-slate-200 bg-white"><div class="border-b p-5"><h2 class="font-bold">Dokumen identitas</h2><p class="mt-1 text-sm text-slate-500">Ditolak? Unggah ulang dari sini — dokumen tersimpan privat dan hanya diperiksa tim verifikasi.</p></div><div class="divide-y">@forelse($documents as $document)<div class="flex flex-wrap items-center justify-between gap-4 p-5"><div><strong>{{ ['ktp' => 'KTP', 'sim' => 'SIM', 'sim_a' => 'SIM A', 'selfie' => 'Selfie dengan KTP'][$document->document_type] ?? ucfirst($document->document_type) }}</strong>@if($document->rejection_reason)<p class="mt-1 text-sm text-red-600">Alasan penolakan: {{ $document->rejection_reason }}</p>@elseif($document->verified_at)<p class="mt-1 text-sm text-emerald-600">Diverifikasi {{ $document->verified_at->format('d M Y') }}</p>@endif</div><div class="flex items-center gap-3"><x-portal.status-badge :status="$document->status" type="document" />@if($document->status !== 'verified')<form method="post" action="{{ route('portal.documents.reupload', $document) }}" enctype="multipart/form-data" data-doc-form>@csrf<label class="cursor-pointer rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-slate-700" data-doc-label>Unggah ulang<input type="file" name="document" accept="image/jpeg,image/png,image/webp" class="hidden" data-doc-input></label><span class="hidden text-xs font-semibold text-slate-500" data-doc-info></span>@endif</div></div>@empty<div class="p-8 text-center text-slate-500">Belum ada dokumen. Unggah KTP & SIM A saat checkout untuk mempercepat verifikasi.</div>@endforelse</div></section>
<script>
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('[data-doc-form]').forEach((form) => {
    const input = form.querySelector('[data-doc-input]');
    const label = form.querySelector('[data-doc-label]');
    const info = form.querySelector('[data-doc-info]');
    input?.addEventListener('change', () => {
      const f = input.files?.[0];
      if (!f) return;
      if (f.size > 4 * 1024 * 1024) {
        info.textContent = 'Maks 4MB — pilih file lebih kecil (' + (f.size / 1048576).toFixed(1) + 'MB).';
        info.classList.remove('hidden');
        info.classList.add('text-red-600');
        input.value = '';
        return;
      }
      info.textContent = 'Mengunggah ' + f.name + ' (' + Math.max(1, Math.round(f.size / 1024)) + ' KB)…';
      info.classList.remove('hidden');
      label.classList.add('opacity-60', 'pointer-events-none');
      label.textContent = 'Mengunggah…';
      form.submit();
    });
  });
});
</script>
@endsection
